site_name: Dynamics Evolution - Gustavo Barboza Blanco

theme:
  name: "material"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js 
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Introducción: index.md
  - Método Numérico: explanation.md
  - Tutorial: tutoriales.md
  - Documentación: reference.md

plugins: 
  - mkdocstrings